name: compressed-size
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-store
        run: echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - name: Use pnpm store
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: ${{ steps.pnpm-store.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
      
      - name: Build GraphQL-Web-Lite
        run: pnpm run build

      - name: compressed-size-action
        uses: preactjs/compressed-size-action@v2
        with:
          pattern: '{scripts/buildenv/dist-graphql/assets/index.js,scripts/buildenv/dist-lite/assets/index.js}'
          build-script: size-check
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
